"""PCI-DSS gateway architecture diagram (non-Mermaid).

Generated by design agent | 2026-02-13
Contract: azure-diagrams skill (deterministic LR layout, naming conventions, quality gate).
"""

from diagrams import Cluster, Diagram, Edge
from diagrams.azure.compute import ContainerRegistries, KubernetesServices
from diagrams.azure.database import CosmosDb, DatabaseForPostgresqlServers
from diagrams.azure.identity import ActiveDirectory
from diagrams.azure.integration import APIManagement, ServiceBus
from diagrams.azure.monitor import ApplicationInsights, LogAnalyticsWorkspaces, Monitor
from diagrams.azure.network import DDOSProtectionPlans, Firewall, FrontDoors
from diagrams.azure.security import KeyVaults
from diagrams.onprem.client import Users
from diagrams.onprem.network import Internet

graph_attr = {
    "bgcolor": "white",
    "pad": "0.5",
    "nodesep": "0.8",
    "ranksep": "1.0",
    "splines": "ortho",
    "fontsize": "14",
    "labelloc": "t",
    "label": "PCI-DSS Payment Gateway | swedencentral | 10k TPS",
}

cluster_attr = {
    "style": "rounded",
    "fontsize": "12",
}

with Diagram(
    "pci-dss-gw",
    filename="agent-output/pci-dss-gw/03-des-diagram",
    show=False,
    direction="LR",
    outformat="png",
    graph_attr=graph_attr,
):
    with Cluster("clu_ext_global", graph_attr=cluster_attr):
        n_edge_users = Users("Merchants")
        n_edge_cardnets = Internet("Card Networks")

    with Cluster("clu_tier_edge", graph_attr=cluster_attr):
        n_edge_ddos = DDOSProtectionPlans("DDoS Protect")
        n_edge_fd = FrontDoors("Front Door + WAF")

    with Cluster("clu_net_hub", graph_attr=cluster_attr):
        n_sec_fw = Firewall("Firewall Premium")

    with Cluster("clu_net_spoke_cde", graph_attr=cluster_attr):
        n_int_apim = APIManagement("APIM Premium")
        n_app_aks = KubernetesServices("AKS Standard")

        with Cluster("clu_tier_data", graph_attr=cluster_attr):
            n_data_pg = DatabaseForPostgresqlServers("PostgreSQL Flex")
            n_data_cosmos = CosmosDb("Cosmos DB")

        with Cluster("clu_tier_sec", graph_attr=cluster_attr):
            n_sec_kv = KeyVaults("Key Vault HSM")
            n_id_entra = ActiveDirectory("Entra ID")
            n_ops_acr = ContainerRegistries("ACR Premium")

        n_int_sb = ServiceBus("Service Bus")

    with Cluster("clu_tier_ops", graph_attr=cluster_attr):
        n_ops_appi = ApplicationInsights("App Insights")
        n_ops_log = LogAnalyticsWorkspaces("Log Analytics")
        n_ops_mon = Monitor("Azure Monitor")

    e_runtime = Edge(color="#1565C0", style="bold")
    e_control = Edge(color="#E65100", style="dashed")
    e_observe = Edge(color="#6A1B9A", style="dotted")

    n_edge_users >> Edge(label="request", **e_runtime.attrs) >> n_edge_fd
    n_edge_ddos - Edge(label="control", **e_control.attrs) - n_edge_fd
    n_edge_fd >> Edge(label="request", **e_runtime.attrs) >> n_sec_fw
    n_sec_fw >> Edge(label="request", **e_runtime.attrs) >> n_int_apim
    n_int_apim >> Edge(label="request", **e_runtime.attrs) >> n_app_aks

    n_app_aks >> Edge(label="write", **e_runtime.attrs) >> n_data_pg
    n_app_aks >> Edge(label="read", **e_runtime.attrs) >> n_data_cosmos
    n_app_aks >> Edge(label="event", **e_runtime.attrs) >> n_int_sb
    n_int_sb >> Edge(label="event", **e_runtime.attrs) >> n_app_aks

    n_app_aks >> Edge(label="secret", **e_control.attrs) >> n_sec_kv
    n_app_aks >> Edge(label="auth", **e_control.attrs) >> n_id_entra
    n_ops_acr >> Edge(label="admin", **e_control.attrs) >> n_app_aks
    n_app_aks >> Edge(label="request", **e_runtime.attrs) >> n_edge_cardnets

    n_app_aks >> Edge(label="telemetry", **e_observe.attrs) >> n_ops_appi
    n_int_apim >> Edge(label="telemetry", **e_observe.attrs) >> n_ops_log
    n_sec_fw >> Edge(label="telemetry", **e_observe.attrs) >> n_ops_log
    n_data_pg >> Edge(label="telemetry", **e_observe.attrs) >> n_ops_log
    n_ops_appi >> Edge(label="telemetry", **e_observe.attrs) >> n_ops_mon
