"""Step 4 deployment dependency diagram (clean view, non-Mermaid).

Generated by design agent | 2026-02-13
Purpose: readable module dependency map with minimal crossing edges.
"""

from diagrams import Cluster, Diagram, Edge
from diagrams.azure.compute import ContainerRegistries, KubernetesServices
from diagrams.azure.database import CosmosDb, DatabaseForPostgresqlServers
from diagrams.azure.devops import Pipelines
from diagrams.azure.identity import ActiveDirectory
from diagrams.azure.integration import APIManagement, ServiceBus
from diagrams.azure.monitor import ApplicationInsights, LogAnalyticsWorkspaces
from diagrams.azure.network import Firewall, FrontDoors, VirtualNetworks
from diagrams.azure.security import KeyVaults

graph_attr = {
    "bgcolor": "white",
    "pad": "0.6",
    "nodesep": "1.0",
    "ranksep": "1.25",
    "splines": "polyline",
    "fontsize": "14",
    "labelloc": "t",
    "label": "Step 4 Deployment Dependencies | pci-dss-gw",
}

cluster_attr = {"style": "rounded", "fontsize": "12"}

with Diagram(
    "pci-dss-gw-dependencies",
    filename="agent-output/pci-dss-gw/04-dependency-diagram",
    show=False,
    direction="LR",
    outformat="png",
    graph_attr=graph_attr,
):
    with Cluster("clu_tier_orchestration", graph_attr=cluster_attr):
        n_ops_pipeline_main = Pipelines("main.bicep")

    with Cluster("clu_tier_phase1_foundation", graph_attr=cluster_attr):
        n_int_network_hub = VirtualNetworks("networking-hub")
        n_int_network_spoke = VirtualNetworks("networking-spoke")
        n_ops_monitor_workspace = LogAnalyticsWorkspaces("monitoring")
        n_id_entra_uami = ActiveDirectory("identity")

    with Cluster("clu_tier_phase2_security", graph_attr=cluster_attr):
        n_sec_keyvault_core = KeyVaults("key-vault")
        n_sec_firewall_hub = Firewall("firewall")

    with Cluster("clu_tier_phase3_data", graph_attr=cluster_attr):
        n_data_postgres_primary = DatabaseForPostgresqlServers("postgresql")
        n_data_cosmos_session = CosmosDb("cosmos-db")
        n_int_servicebus_tx = ServiceBus("service-bus")
        n_app_acr_images = ContainerRegistries("container-registry")

    with Cluster("clu_tier_phase4_compute", graph_attr=cluster_attr):
        n_app_aks_cluster = KubernetesServices("aks")

    with Cluster("clu_tier_phase5_edge", graph_attr=cluster_attr):
        n_edge_frontdoor_global = FrontDoors("front-door")
        n_int_apim_gateway = APIManagement("api-management")
        n_ops_appinsights_main = ApplicationInsights("app-insights")

    e_runtime = Edge(color="#1565C0", style="bold", penwidth="1.3")
    e_control = Edge(color="#E65100", style="dashed")
    e_observe = Edge(color="#6A1B9A", style="dotted")

    n_ops_pipeline_main >> e_runtime >> [
        n_int_network_hub,
        n_int_network_spoke,
        n_ops_monitor_workspace,
        n_id_entra_uami,
    ]

    n_int_network_hub >> e_runtime >> [n_sec_firewall_hub, n_sec_keyvault_core]
    n_int_network_spoke >> e_runtime >> [
        n_sec_keyvault_core,
        n_data_postgres_primary,
        n_data_cosmos_session,
        n_int_servicebus_tx,
        n_app_acr_images,
        n_app_aks_cluster,
        n_int_apim_gateway,
    ]

    n_id_entra_uami >> Edge(label="auth", **e_control.attrs) >> n_sec_keyvault_core
    n_sec_keyvault_core >> Edge(label="secret", **e_control.attrs) >> n_data_postgres_primary
    n_sec_keyvault_core >> Edge(label="secret", **e_control.attrs) >> n_data_cosmos_session
    n_sec_keyvault_core >> Edge(label="secret", **e_control.attrs) >> n_int_servicebus_tx
    n_sec_keyvault_core >> Edge(label="secret", **e_control.attrs) >> n_app_aks_cluster
    n_sec_keyvault_core >> Edge(label="secret", **e_control.attrs) >> n_int_apim_gateway

    n_app_acr_images >> Edge(label="admin", **e_control.attrs) >> n_app_aks_cluster
    n_ops_monitor_workspace >> Edge(label="telemetry", **e_observe.attrs) >> n_app_aks_cluster
    n_app_aks_cluster >> e_runtime >> [n_int_apim_gateway, n_edge_frontdoor_global]
    n_sec_firewall_hub >> e_runtime >> n_edge_frontdoor_global

    n_ops_monitor_workspace >> Edge(label="telemetry", **e_observe.attrs) >> n_ops_appinsights_main
    n_ops_appinsights_main >> Edge(label="telemetry", **e_observe.attrs) >> n_int_apim_gateway
