"""Step 4 runtime flow diagram (companion view, non-Mermaid).

Generated by design agent | 2026-02-13
Purpose: runtime-only traffic and control paths, separated from deployment dependencies.
"""

from diagrams import Cluster, Diagram, Edge
from diagrams.azure.compute import KubernetesServices
from diagrams.azure.database import CosmosDb, DatabaseForPostgresqlServers
from diagrams.azure.identity import ActiveDirectory
from diagrams.azure.integration import APIManagement, ServiceBus
from diagrams.azure.monitor import ApplicationInsights, LogAnalyticsWorkspaces, Monitor
from diagrams.azure.network import DDOSProtectionPlans, Firewall, FrontDoors
from diagrams.azure.security import KeyVaults
from diagrams.onprem.client import Users
from diagrams.onprem.network import Internet

graph_attr = {
    "bgcolor": "white",
    "pad": "0.6",
    "nodesep": "1.0",
    "ranksep": "1.25",
    "splines": "polyline",
    "fontsize": "14",
    "labelloc": "t",
    "label": "Step 4 Runtime Flows | pci-dss-gw",
}

cluster_attr = {"style": "rounded", "fontsize": "12"}

with Diagram(
    "pci-dss-gw-runtime",
    filename="agent-output/pci-dss-gw/04-runtime-diagram",
    show=False,
    direction="LR",
    outformat="png",
    graph_attr=graph_attr,
):
    with Cluster("clu_ext_global", graph_attr=cluster_attr):
        n_edge_client_merchant = Users("merchants")
        n_edge_partner_cardnet = Internet("card-network")

    with Cluster("clu_tier_edge", graph_attr=cluster_attr):
        n_edge_ddos_protect = DDOSProtectionPlans("ddos-protect")
        n_edge_frontdoor_global = FrontDoors("front-door")

    with Cluster("clu_net_hub", graph_attr=cluster_attr):
        n_sec_firewall_hub = Firewall("firewall")

    with Cluster("clu_net_spoke_cde", graph_attr=cluster_attr):
        n_int_apim_gateway = APIManagement("api-management")
        n_app_aks_cluster = KubernetesServices("aks")

        with Cluster("clu_tier_data", graph_attr=cluster_attr):
            n_data_postgres_primary = DatabaseForPostgresqlServers("postgresql")
            n_data_cosmos_session = CosmosDb("cosmos-db")
            n_int_servicebus_tx = ServiceBus("service-bus")

        with Cluster("clu_tier_security", graph_attr=cluster_attr):
            n_sec_keyvault_core = KeyVaults("key-vault")
            n_id_entra_workload = ActiveDirectory("entra-id")

    with Cluster("clu_tier_ops", graph_attr=cluster_attr):
        n_ops_appinsights_main = ApplicationInsights("app-insights")
        n_ops_loganalytics_main = LogAnalyticsWorkspaces("log-analytics")
        n_ops_monitor_main = Monitor("azure-monitor")

    e_runtime = Edge(color="#1565C0", style="bold", penwidth="1.3")
    e_control = Edge(color="#E65100", style="dashed")
    e_observe = Edge(color="#6A1B9A", style="dotted")

    n_edge_client_merchant >> Edge(label="request", **e_runtime.attrs) >> n_edge_frontdoor_global
    n_edge_ddos_protect - Edge(label="admin", **e_control.attrs) - n_edge_frontdoor_global
    n_edge_frontdoor_global >> Edge(label="request", **e_runtime.attrs) >> n_sec_firewall_hub
    n_sec_firewall_hub >> Edge(label="request", **e_runtime.attrs) >> n_int_apim_gateway
    n_int_apim_gateway >> Edge(label="request", **e_runtime.attrs) >> n_app_aks_cluster

    n_app_aks_cluster >> Edge(label="write", **e_runtime.attrs) >> n_data_postgres_primary
    n_app_aks_cluster >> Edge(label="read", **e_runtime.attrs) >> n_data_cosmos_session
    n_app_aks_cluster >> Edge(label="event", **e_runtime.attrs) >> n_int_servicebus_tx
    n_int_servicebus_tx >> Edge(label="event", **e_runtime.attrs) >> n_app_aks_cluster

    n_app_aks_cluster >> Edge(label="auth", **e_control.attrs) >> n_id_entra_workload
    n_app_aks_cluster >> Edge(label="secret", **e_control.attrs) >> n_sec_keyvault_core
    n_app_aks_cluster >> Edge(label="request", **e_runtime.attrs) >> n_edge_partner_cardnet

    n_app_aks_cluster >> Edge(label="telemetry", **e_observe.attrs) >> n_ops_appinsights_main
    n_int_apim_gateway >> Edge(label="telemetry", **e_observe.attrs) >> n_ops_loganalytics_main
    n_sec_firewall_hub >> Edge(label="telemetry", **e_observe.attrs) >> n_ops_loganalytics_main
    n_data_postgres_primary >> Edge(label="telemetry", **e_observe.attrs) >> n_ops_loganalytics_main
    n_ops_appinsights_main >> Edge(label="telemetry", **e_observe.attrs) >> n_ops_monitor_main
